### ISSUE TITLE
undefined: gorm.ColumnType On GORM 1.20.4

### ISSUE THREAD

**Issue by microchi** [go-gorm/mysql#10]
Dependabot committed Bump gorm.io/gorm from 1.20.2 to 1.20.4

But @asmeikal Add ColumnType interface On [Commit 635dcc9 In GORM](https://github.com/go-gorm/gorm/commit/635dcc9ad4faa02cf625b050a7b439bd44292407)

Not Yet Release ON 1.20.4

We Will Get undefined: gorm.ColumnType Error When Building
![螢幕擷取畫面 2020-10-22 173855](https://user-images.githubusercontent.com/13308256/96853899-7b821900-148d-11eb-9b3c-688b34ee8e86.png)

**Comment by jinzhu** [comment]
released GORM v1.20.5

**Comment by microchi** [comment]
Thank You For Awesome Project!!!
