### ISSUE TITLE
Migrator Update Table

### ISSUE THREAD

**Issue by zhgqiang** [go-gorm/mysql#134]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description

![image](https://github.com/go-gorm/mysql/assets/8361981/394ba544-3262-486b-abcb-964a1cac2327)
当expr切换数据库去使用时，expr包含有数据库信息，数据去查询是 table 在这里不应该在指定，指定后报
![image](https://github.com/go-gorm/mysql/assets/8361981/1ef8ebb1-cdab-41a5-80bb-1a6ee6e8d908)
去掉后正常
![image](https://github.com/go-gorm/mysql/assets/8361981/82d42122-5d85-41fd-973b-37d5f34512ab)

**Comment by saeidee** [comment]
Can you please create the playground PR or at least add proper details?

**Comment by jinzhu** [comment]
Seems will be fixed by this PR?
