### ISSUE TITLE
v1.0.3 undefined: gorm.ColumnType

### ISSUE THREAD

**Issue by Reasno** [go-gorm/mysql#14]
## Description

in v1.0.3, during boot up:

../go/pkg/mod/gorm.io/driver/mysql@v1.0.3/migrator.go:192:65: undefined: gorm.ColumnType
../go/pkg/mod/gorm.io/driver/mysql@v1.0.3/migrator.go:193:23: undefined: gorm.ColumnType

errors disappeared after downgrading to v1.0.2.

**Comment by jinzhu** [comment]
upgrade gorm
