### ISSUE TITLE
v1.0.4 requires gorm.io/gorm@v1.20.12(unknown revision)

### ISSUE THREAD

**Issue by michaelzx** [go-gorm/mysql#23]
## Description

go get: gorm.io/driver/mysql@v1.0.4 requires
        gorm.io/gorm@v1.20.12: reading gorm.io/gorm/go.mod at revision v1.20.12: unknown revision v1.20.12

**Comment by CherishNA** [comment]
I also have this problem，Have you solved it？

**Comment by ipfans** [comment]
gorm.io/gorm@v1.20.12 is not release yet. You can set your gorm.io/driver/mysql version pin to v1.0.3 or waiting for release.

**Comment by jinzhu** [comment]
just published, sorry for the issue.
