### ISSUE TITLE
update_at time is not consistent

### ISSUE THREAD

**Issue by AWaterColorPen** [go-gorm/mysql#24]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/288

## Description

For example: 
when we call updates method, user.update_at is "2021-02-26 20:47:16.823720459Z" .
But the UPDATE sql uses "update_at"="2021-02-26 20:47:16.824Z",  and SELECT sql uses "update_at"="2021-02-26 20:47:16.823Z"

update_at is not consistent.

I think update_at should be consistent. And it should be no error for this case

**Comment by jinzhu** [comment]
this should been fixed.
