### ISSUE TITLE
DSN Connector URL with special characters

### ISSUE THREAD

**Issue by RohanPoojary** [go-gorm/mysql#35]
Hi Gophers, Firstly I will like to thank gorm developers for building this purely fantastic ORM library. 
My question is how do I delimit the special characters in the MySQL DSN URL? The password that I'm using contains `@` & `#` symbols which is causing this issue. I have also tried URL encoding the password, but still no effect. Kindly need your help with this, thanks :) 

DSN Pattern: `<username>:<password>@tcp(<hostname>:<port>)/<database>`

I'm following the below documentation
https://gorm.io/docs/connecting_to_the_database.html

**Comment by rajiv-k** [comment]
@RohanPoojary Checkout this example from the test file: https://github.com/go-sql-driver/mysql/blob/master/dsn_test.go#L47-L50
as the doc you're following mentions they use the same DSN parser.

Also I tried adding an additional test case with a password value containing `@` and `#`, the test seems to work fine. Could you post the DSN that you're using? (ofc remove any sensitive details :) )

**Comment by kadalcj** [comment]
> @RohanPoojary Checkout this example from the test file: https://github.com/go-sql-driver/mysql/blob/master/dsn_test.go#L47-L50 as the doc you're following mentions they use the same DSN parser.
> 
> Also I tried adding an additional test case with a password value containing `@` and `#`, the test seems to work fine. Could you post the DSN that you're using? (ofc remove any sensitive details :) )

Hi @rajiv-k , could you please elaborate more regarding your answer. Still new on Golang and it quite confusing for me to figure it out. How did exactly we implement like for my case the password was having special character `@`? Thank you :)

**Comment by kadalcj** [comment]
Ah, sorry to bothering in this closed issue. I just figured it out. Thanks

**Comment by dbkblk** [comment]
Hi,
In my case, this is a # and following the link of DSN tests, I don't see any test case with that char....
