### ISSUE TITLE
Named Attributes in Migrator

### ISSUE THREAD

**Issue by krotscheck** [go-gorm/mysql#41]
Hi there! I've build an RDS Data API SQL Driver (Aurora Serverless) so I don't have to pay for all the VPC resources necessary to access a cluster directly. The challenge I'm facing now is that the data api's ExecuteStatement only supports named parameters, not [ordinal ones](https://docs.aws.amazon.com/rdsdataservice/latest/APIReference/API_ExecuteStatement.html); and since the Migrator uses ordinal parameter substitution, migration simply doesn't work.

I have a little time to put towards switching the Migrator in the Mysql dialector over to named parameters, is that something you'd be willing to accept?

**Comment by mrusme** [comment]
It's a bummer nobody took the time to get back to @krotscheck on this frankly speaking - especially since he apparently has already invested time to actually build an integration that others (including me, right now) could really use.

**Comment by krotscheck** [comment]
Oh, I've engineered around this problem a while ago. Fact is that using named parameters is considered a best practice when assembling SQL queries, so asking the migrators to switch over is a little bit of a silly request.

Having said that, I've

**Comment by krotscheck** [comment]
Here's the driver, since you said you needed it. https://github.com/krotscheck/go-rds-driver

**Comment by jinzhu** [comment]
Maybe wrap the driver like https://github.com/go-gorm/sqlserver/blob/3e974a4894f539604fabe0ea31355b688a038f40/sqlserver.go#L115-L118 should works?

**Comment by krotscheck** [comment]
Naah, no need. I'll close the issue here as the SQL Driver interface gives me the inputs I need to properly convert it.
