### ISSUE TITLE
MySQL 8.0 - Deprecate VALUES syntax in INSERT ... ON DUPLICATE KEY UPDATE

### ISSUE THREAD

**Issue by marvinwhite** [go-gorm/mysql#47]
## Describe the feature

On MySQL 8.0 server the waring message is raised:
```
1287 'VALUES function' is deprecated and will be removed in a future release. 
Please use an alias (INSERT INTO ... VALUES (...) AS alias) and replace 
VALUES(col) in the ON DUPLICATE KEY UPDATE clause with alias.col instead
```
More details at [MySQL work log](https://dev.mysql.com/worklog/task/?id=13325)

## Motivation
I don't know which future release will remove this function but seems reasonable to implement the new supported alias in the driver in case.

**Comment by jinzhu** [comment]
Thank you for the information, and will work on that once the values function is not supported. the new syntax is not supported for mostly running db services currently.
