### ISSUE TITLE
support tidb AUTO_RANDOM tag 

### ISSUE THREAD

**Issue by dovefi** [go-gorm/mysql#53]
## Describe the feature
support `auto_random` tag

## Motivation
tidb use primary key with `AUTO_RANDOM` tag to avoid hot spot, but gorm doesn't seem to support it！

## Related Issues

https://docs.pingcap.com/zh/tidb/stable/auto-random

**Comment by jinzhu** [comment]
Hi ,

You can set column's data type with the `type` tag. refer https://gorm.io/docs/models.html#Fields-Tags
