### ISSUE TITLE
undefined: migrator.ColumnType

### ISSUE THREAD

**Issue by KamleshArya** [go-gorm/mysql#63]
We are getting following error after new update:

../../../pkg/mod/gorm.io/driver/mysql@v1.3.0/migrator.go:175:23: undefined: migrator.ColumnType

**Comment by ReianLin** [comment]
undefined: migrator.ColumnType

**Comment by jinzhu** [comment]
Upgrade gorm.io/gorm and gorm.io/driver/mysql
