### ISSUE TITLE
Column missing AutoIncrement method

### ISSUE THREAD

**Issue by wclssdn** [go-gorm/mysql#71]
## Description

Versions: 

- `gorm.io/gorm v1.23.3`
- `gorm.io/driver/mysql v1.2.3` // indirect

get this error message

```
# gorm.io/driver/mysql
/Users/nemo/go/pkg/mod/gorm.io/driver/mysql@v1.2.3/migrator.go:224:38: cannot use column (variable of type Column) as type gorm.ColumnType in argument to append:
        Column does not implement gorm.ColumnType (missing AutoIncrement method)
```

if i change version to  `gorm.io/gorm v1.22.5`, it works well. (Another project use this version, and it's works.)

**Comment by wclssdn** [comment]
I'm sorry to haven't provide a GORM Playground Link.

**Comment by jinzhu** [comment]
`Upgrade` to latest version should works.
