### ISSUE TITLE
Clause.(clause.Returning{}) dosen't work in a delete opertaion

### ISSUE THREAD

**Issue by Zacama** [go-gorm/mysql#85]
## Clause.(clause.Returning{}) dosen't active in a delete opertaion

**Version: gorm 1.23.8 and golang 1.18.3**

Sorry for my poor English...

I try to use Clause.(clause.Returning{}) to returning the obj which has been deleted. But It doesn't work.
![image](https://user-images.githubusercontent.com/50320281/180708220-08c68fc7-cc5c-4ce2-8ba7-9d4b4988117e.png)
At first, I thought the database dose not support Returning. So I try it by raw sql, it works.
![image](https://user-images.githubusercontent.com/50320281/180708041-a50bc232-e8a6-458f-a381-24d6f194c0ee.png)
Then, I try to find the problem by reading source code and debug it. Limited by my skill level, I can only find out the final raw sql (generated by gorm) does not contain `RETURNING` .
![image](https://user-images.githubusercontent.com/50320281/180709378-bbd40866-4036-4d7a-bf45-00978aa50517.png)
Partof callback.go/Execute function
![image](https://user-images.githubusercontent.com/50320281/180709657-df90a051-ccc3-4a80-89c4-3ba522ff2452.png)
statement.go/AddClause function
![image](https://user-images.githubusercontent.com/50320281/180709872-65b007e1-77ab-4943-ab7d-636449ccf2f9.png)
But it can be seen from the screenshot that `RETURNING` is added to db.Statement.Clauses map but it seems like no subsequent code to use it.
I don't know which step is wrong. If anyone could help me take a look, it would be greatly appreciated.

## Expected answer

Just want got the return successfully.

**Comment by a631807682** [comment]
returning may need to be specified depending on the version, need confirm.
https://github.com/go-gorm/mysql/blob/master/mysql.go#L41

**Comment by Zacama** [comment]
@a631807682 I want to confirm that do you mean I should able to use like this?
`
        db, _ := gorm.Open(mysql.Open(dsn))
        // after init, register it. 
	callbacks.RegisterDefaultCallbacks(db, &callbacks.Config{
		CreateClauses: []string{"INSERT", "VALUES", "ON CONFLICT", "RETURNING"},
		QueryClauses:  mysql.QueryClauses,
		UpdateClauses: mysql.UpdateClauses,
		DeleteClauses: mysql.DeleteClauses,
	})
`

**Comment by a631807682** [comment]
@Zacama  yes

**Comment by Zacama** [comment]
@a631807682 It returns a lot of warning ...
![image](https://user-images.githubusercontent.com/50320281/183028712-7bb0bb73-42b4-4f74-bfe3-418f43accd76.png)

**Comment by a631807682** [comment]
how about?
```go
db, _ := gorm.Open(mysql.Open(dsn))
createCallback := db.Callback().Create()
createCallback.Clauses = []string{"INSERT", "VALUES", "ON CONFLICT", "RETURNING"}
```

**Comment by Zacama** [comment]
@a631807682 yeah, It can print right rawsql now.
![image](https://user-images.githubusercontent.com/50320281/183326372-8c3f288d-bb0f-4dfa-af61-faa174a01eb4.png)
Incredible... it can only print right right rawsql.
![image](https://user-images.githubusercontent.com/50320281/183326487-09c844cf-1601-4cf4-9447-d13bb55266d9.png)
![image](https://user-images.githubusercontent.com/50320281/183326520-015f1d9d-1372-494d-85db-37b91cc9a08b.png)
But when I test in mysql command line. It return correctly.
![image](https://user-images.githubusercontent.com/50320281/183326769-88c2e7d1-77d5-4dd1-afc5-2d0759b7b148.png)

**Comment by Zacama** [comment]
I tried to find out what the problem is, but I can't find it...
So I try to use rawsql. Amazingly, it worked
![image](https://user-images.githubusercontent.com/50320281/183339714-5fb55cc4-ca9e-4515-a0cd-e8d58d5e1c97.png)
![image](https://user-images.githubusercontent.com/50320281/183339783-2bf47834-8c4f-467d-8fc9-2966cdc7adde.png)

**Comment by Zacama** [comment]
@a631807682 Really, thank you very very much for helping me solve this problem😊.  I achieved my goal.  I don't quite understand the process of closing the issue. If I can close this issue, I'm ready to close it.

**Comment by a631807682** [comment]
@Zacama I think we can keep it open and wait for someone to implement it.

**Comment by Zacama** [comment]
@a631807682 OK, we keep it.
